### ISSUE TITLE
Compatibility warning: not verified for v10

### ISSUE THREAD

**Issue by yjeroen** [brunocalado/incompleteadventurer#1]
![image](https://user-images.githubusercontent.com/1303988/200175640-dad05001-a7a4-4f7f-b5bc-c701598bd0b0.png)

Would be great if the module.json could be updated if the module is compatible with Foundry V10.

**Comment by brunocalado** [comment]
Remove this module. Use dungeon world extra content

Em dom, 6 de nov de 2022 11:11, Jeroen den Haan ***@***.***>
escreveu:

**Comment by yjeroen** [comment]
Thanks
